"""Add post date to blog

Revision ID: b8f9d89a437e
Revises: 7649015ecfdb
Create Date: 2019-11-30 11:00:47.300615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f9d89a437e'
down_revision = '7649015ecfdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'created')
    # ### end Alembic commands ###
